services:
  sitewatch:
    build:
      context: ../../
      dockerfile: deployments/docker/Dockerfile.dev
    container_name: sitewatch-dev
    ports:
      - "8080:8080"
    volumes:
      # Live reload für Development
      - ../../:/app
      - /app/bin  # Exclude bin directory
    environment:
      - GO_ENV=development
      - LOG_LEVEL=debug
      # Server configuration
      - SITEWATCH_SERVER_HOST=${SITEWATCH_SERVER_HOST:-0.0.0.0}
      - SITEWATCH_SERVER_PORT=${SITEWATCH_SERVER_PORT:-8080}
      # Storage configuration (memory for dev)
      - SITEWATCH_STORAGE_TYPE=${SITEWATCH_STORAGE_TYPE:-memory}
      - SITEWATCH_STORAGE_MAX_MEMORY_LOGS=${SITEWATCH_STORAGE_MAX_MEMORY_LOGS:-1000}
      # Metrics configuration
      - SITEWATCH_METRICS_ENABLED=${SITEWATCH_METRICS_ENABLED:-true}
      - SITEWATCH_METRICS_PATH=${SITEWATCH_METRICS_PATH:-/metrics}
      # Authentication (usually disabled for dev)
      - SITEWATCH_AUTH_ENABLED=${SITEWATCH_AUTH_ENABLED:-false}
      # Config paths
      - SITEWATCH_CONFIG_PATH=${SITEWATCH_CONFIG_PATH:-configs/config.yaml}
      - SITEWATCH_SITES_PATH=${SITEWATCH_SITES_PATH:-configs/sites.yaml}
    restart: unless-stopped